### ISSUE TITLE
Command ["bin/rails db:setup"] failed

### ISSUE THREAD

**Issue by nihartn** [projectblacklight/code4lib_precon_demo#18]
Hi Chris,

When using the Getting Started instructions, I'm getting an error pertaining to the rsolr gem - included the console info from the bundle install part as well.
Was using Ruby 2.4.0/Rails 5.0.1, got the same error using Ruby 2.3.3/Rails 4.2.7.1
And, getting the same error when running `rake --tasks`
Thoughts?

```
libadmin@libsys-c4l-blacklight:~$ cd code4lib_precon_demo/
libadmin@libsys-c4l-blacklight:~/code4lib_precon_demo$ bin/setup
== Checking dependencies ==
== Installing dependencies ==
The git source `git://github.com/projectblacklight/blacklight.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
git://github.com/projectblacklight/blacklight.git (at master@7c4d63c) is not yet checked out. Run `bundle install` first.
The git source `git://github.com/projectblacklight/blacklight.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Fetching git://github.com/projectblacklight/blacklight.git
Installing rake 12.0.0
Using concurrent-ruby 1.0.4
Using i18n 0.8.1
Installing minitest 5.10.1
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Installing rack 2.0.1
Installing nio4r 1.2.1 with native extensions
Installing websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Installing arel 7.1.4
Installing public_suffix 2.0.5
Installing execjs 2.7.0
Installing bcrypt 3.1.11 with native extensions
Installing sass 3.4.23
Installing kaminari-core 1.0.1
Using bundler 1.14.5
Installing method_source 0.8.2
Using thor 0.19.4
Installing library_stdnums 1.4.1
Installing scrub_rb 1.0.1
Installing unf_ext 0.0.7.2 with native extensions
Installing dot-properties 0.1.3
Installing hashie 3.5.4
Installing httpclient 2.8.3
Installing slop 3.6.0
Installing yell 2.0.7
Installing byebug 9.0.6 with native extensions
Installing coffee-script-source 1.12.2
Installing debug_inspector 0.0.2 with native extensions
Installing orm_adapter 0.5.0
Installing diff-lcs 1.3
Installing multipart-post 2.0.0
Installing ffi 1.9.17 with native extensions
Installing multi_json 1.12.1
Installing rb-fsevent 0.9.8
Installing mysql2 0.4.5 with native extensions
Installing puma 3.7.1 with native extensions
Installing rspec-support 3.5.0
Installing ruby-progressbar 1.8.1
Installing rubyzip 1.2.1
Installing tilt 2.0.6
Installing sqlite3 1.3.13 with native extensions
Installing turbolinks-source 5.0.0
Using tzinfo 1.2.2
Using nokogiri 1.7.0.1
Using rack-test 0.6.3
Using sprockets 3.7.1
Installing warden 1.2.7
Installing websocket-driver 0.6.5 with native extensions
Using mime-types 3.1
Installing addressable 2.5.0
Installing autoprefixer-rails 6.7.5
Installing uglifier 3.0.4
Installing unf 0.1.4
Installing coffee-script 2.4.1
Installing faraday 0.11.0
Installing rb-inotify 0.9.8
Installing rspec-core 3.5.4
Installing rspec-expectations 3.5.0
Installing rspec-mocks 3.5.0
Installing turbolinks 5.0.1
Installing activesupport 5.0.1
Using loofah 2.0.3
Installing xpath 2.0.0
Using mail 2.6.4
Installing bootstrap 4.0.0.alpha6
Installing marc 1.0.0
Installing rsolr 2.0.0.pre2
Installing solr_wrapper 0.21.0
Installing listen 3.0.8
Installing rspec 3.5.0
Installing rails-dom-testing 2.0.2
Using globalid 0.3.7
Installing activemodel 5.0.1
Installing deprecation 1.0.0
Installing jbuilder 2.6.2
Installing spring 2.0.1
Using rails-html-sanitizer 1.0.3
Installing capybara 2.12.0
Installing marc-fastxmlwriter 1.0.0
Installing activejob 5.0.1
Installing activerecord 5.0.1
Installing spring-watcher-listen 2.0.1
Installing actionview 5.0.1
Installing traject 2.3.3
Installing kaminari-activerecord 1.0.1
Installing actionpack 5.0.1
Installing kaminari-actionview 1.0.1
Installing actioncable 5.0.1
Installing actionmailer 5.0.1
Installing railties 5.0.1
Using sprockets-rails 3.2.0
Installing kaminari 1.0.1
Installing jquery-rails 4.2.2
Installing coffee-rails 4.2.1
Installing responders 2.3.0
Installing rspec-rails 3.5.2
Installing web-console 3.4.0
Installing rails 5.0.1
Installing sass-rails 5.0.6
Installing twitter-typeahead-rails 0.11.1.pre.corejavascript
Installing devise 4.2.0
Using blacklight 7.0.0.alpha from git://github.com/projectblacklight/blacklight.git (at master@7c4d63c)
Installing devise-guests 0.5.0
Installing blacklight-marc 6.1.1
Bundle complete! 26 Gemfile dependencies, 108 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

== Preparing database ==
rails aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'rsolr'.
Gem Load Error is: uninitialized constant RSolr::Generator
Did you mean?  Enumerator
Backtrace for gem load error is:
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr/json.rb:4:in `<module:JSON>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr/json.rb:3:in `<top (required)>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr.rb:2:in `require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr.rb:2:in `block in <module:RSolr>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr.rb:2:in `each'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr.rb:2:in `<module:RSolr>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr.rb:1:in `<top (required)>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:91:in `require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `each'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `block in require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `each'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler.rb:107:in `require'
/home/libadmin/code4lib_precon_demo/config/application.rb:7:in `<top (required)>'
/home/libadmin/code4lib_precon_demo/Rakefile:4:in `require'
/home/libadmin/code4lib_precon_demo/Rakefile:4:in `<top (required)>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `each'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `block in require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `each'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler.rb:107:in `require'
/home/libadmin/code4lib_precon_demo/config/application.rb:7:in `<top (required)>'
/home/libadmin/code4lib_precon_demo/Rakefile:4:in `require'
/home/libadmin/code4lib_precon_demo/Rakefile:4:in `<top (required)>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
NameError: uninitialized constant RSolr::Generator
Did you mean?  Enumerator
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr/json.rb:4:in `<module:JSON>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr/json.rb:3:in `<top (required)>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr.rb:2:in `require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr.rb:2:in `block in <module:RSolr>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr.rb:2:in `each'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr.rb:2:in `<module:RSolr>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/rsolr-2.0.0.pre2/lib/rsolr.rb:1:in `<top (required)>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:91:in `require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `each'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `block in require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `each'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `require'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler.rb:107:in `require'
/home/libadmin/code4lib_precon_demo/config/application.rb:7:in `<top (required)>'
/home/libadmin/code4lib_precon_demo/Rakefile:4:in `require'
/home/libadmin/code4lib_precon_demo/Rakefile:4:in `<top (required)>'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/libadmin/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==
```

**Comment by cbeer** [comment]
Thanks @nihartn; I think we've fixed that now in master.
