### ISSUE TITLE
"uninitialized constant RSolr::Field" during db:setup

### ISSUE THREAD

**Issue by akhtars** [projectblacklight/code4lib_precon_demo#25]
Hi there, apologies for the late testing and reporting on this. Similar to #18, but a different RSolr-related message. Encountered this with Ruby 2.4.0/Rails 5.0.1 on a couple of different devices. Any recommendations would be appreciated, but I realize it might be too late to find a fix. Thanks for setting up this workshop!

```
shaun@shaun-VirtualBox:~/Documents/code4lib_precon_demo$ bin/setup
== Checking dependencies ==
== Installing dependencies ==
The git source `git://github.com/projectblacklight/blacklight.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
git://github.com/projectblacklight/blacklight.git (at master@4e5af82) is not yet
checked out. Run `bundle install` first.
The git source `git://github.com/projectblacklight/blacklight.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching git://github.com/projectblacklight/blacklight.git
Using rake 12.0.0
Installing concurrent-ruby 1.0.4
Using i18n 0.8.1
Using minitest 5.10.1
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Installing public_suffix 2.0.5
Using execjs 2.7.0
Installing bcrypt 3.1.11 with native extensions
Using sass 3.4.23
Installing kaminari-core 1.0.1
Using bundler 1.14.6
Using method_source 0.8.2
Using thor 0.19.4
Installing library_stdnums 1.4.1
Installing scrub_rb 1.0.1
Installing unf_ext 0.0.7.2 with native extensions
Installing dot-properties 0.1.3
Installing hashie 3.5.5
Installing httpclient 2.8.3
Installing slop 3.6.0
Installing yell 2.0.7
Using byebug 9.0.6
Using coffee-script-source 1.12.2
Using debug_inspector 0.0.2
Installing orm_adapter 0.5.0
Installing diff-lcs 1.3
Installing multipart-post 2.0.0
Installing ffi 1.9.17 with native extensions
Using multi_json 1.12.1
Using rb-fsevent 0.9.8
Using puma 3.7.1
Installing rspec-support 3.5.0
Installing ruby-progressbar 1.8.1
Installing rubyzip 1.2.1
Using tilt 2.0.6
Installing sqlite3 1.3.13 with native extensions
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Using nokogiri 1.7.0.1
Using rack-test 0.6.3
Using sprockets 3.7.1
Installing warden 1.2.7
Using websocket-driver 0.6.5
Using mime-types 3.1
Installing addressable 2.5.0
Installing autoprefixer-rails 6.7.5
Installing uglifier 3.0.4
Installing unf 0.1.4
Using coffee-script 2.4.1
Installing faraday 0.11.0
Using rb-inotify 0.9.8
Installing rspec-core 3.5.4
Installing rspec-expectations 3.5.0
Installing rspec-mocks 3.5.0
Using turbolinks 5.0.1
Using activesupport 5.0.1
Using loofah 2.0.3
Installing xpath 2.0.0
Using mail 2.6.4
Installing bootstrap 4.0.0.alpha6
Installing marc 1.0.0
Installing rsolr 2.0.0.pre3
Installing solr_wrapper 0.21.0
Using listen 3.0.8
Installing rspec 3.5.0
Using rails-dom-testing 2.0.2
Using globalid 0.3.7
Using activemodel 5.0.1
Installing deprecation 1.0.0
Using jbuilder 2.6.3
Using spring 2.0.1
Using rails-html-sanitizer 1.0.3
Installing capybara 2.12.1
Installing marc-fastxmlwriter 1.0.0
Using activejob 5.0.1
Using activerecord 5.0.1
Using spring-watcher-listen 2.0.1
Using actionview 5.0.1
Installing traject 2.3.3
Installing kaminari-activerecord 1.0.1
Using actionpack 5.0.1
Installing kaminari-actionview 1.0.1
Using actioncable 5.0.1
Using actionmailer 5.0.1
Using railties 5.0.1
Using sprockets-rails 3.2.0
Installing kaminari 1.0.1
Using jquery-rails 4.2.2
Using coffee-rails 4.2.1
Installing responders 2.3.0
Installing rspec-rails 3.5.2
Using web-console 3.4.0
Using rails 5.0.1
Using sass-rails 5.0.6
Installing twitter-typeahead-rails 0.11.1.pre.corejavascript
Installing devise 4.2.0
Using blacklight 7.0.0.alpha from git://github.com/projectblacklight/blacklight.git (at master@4e5af82)
Installing devise-guests 0.5.0
Installing blacklight-marc 6.1.1
Bundle complete! 25 Gemfile dependencies, 107 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

== Preparing database ==
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
rails aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'rsolr'.
Gem Load Error is: uninitialized constant RSolr::Field
Did you mean?  File
Backtrace for gem load error is:
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rsolr-2.0.0.pre3/lib/rsolr/xml.rb:5:in `<module:Xml>'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rsolr-2.0.0.pre3/lib/rsolr/xml.rb:3:in `<top (required)>'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rsolr-2.0.0.pre3/lib/rsolr.rb:2:in `require'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rsolr-2.0.0.pre3/lib/rsolr.rb:2:in `block in <module:RSolr>'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rsolr-2.0.0.pre3/lib/rsolr.rb:2:in `each'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rsolr-2.0.0.pre3/lib/rsolr.rb:2:in `<module:RSolr>'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rsolr-2.0.0.pre3/lib/rsolr.rb:1:in `<top (required)>'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/home/shaun/Documents/code4lib_precon_demo/config/application.rb:7:in `<top (required)>'
/home/shaun/Documents/code4lib_precon_demo/Rakefile:4:in `require'
/home/shaun/Documents/code4lib_precon_demo/Rakefile:4:in `<top (required)>'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/shaun/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
/home/shaun/Documents/code4lib_precon_demo/config/application.rb:7:in `<top (required)>'
/home/shaun/Documents/code4lib_precon_demo/Rakefile:4:in `require'
/home/shaun/Documents/code4lib_precon_demo/Rakefile:4:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
NameError: uninitialized constant RSolr::Field
Did you mean?  File
/home/shaun/Documents/code4lib_precon_demo/config/application.rb:7:in `<top (required)>'
/home/shaun/Documents/code4lib_precon_demo/Rakefile:4:in `require'
/home/shaun/Documents/code4lib_precon_demo/Rakefile:4:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)

== Command ["bin/rails db:create db:migrate db:setup"] failed ==
```

**Comment by cbeer** [comment]
Thanks, and sorry, I was working a fix through the projects and forgot to update this. I have a branch that ought to work for you (https://github.com/projectblacklight/code4lib_precon_demo/pull/26), or you can just run `bundle update` locally.

**Comment by akhtars** [comment]
I ran `bundle update`, and that did fix it. Thanks for the quick reply!
